name: saurav
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  io: ^1.0.0
  json_serializable: ^4.1.3
  
